"use client";

import Image from "next/image";
import { useCallback, useEffect, useRef, useState } from "react";
import frontImage from "@/assets/reference-images/product-views/product-front.webp";
import insideImage from "@/assets/reference-images/product-views/product-inside.webp";
import hotspotData from "@/knowledge/hotspots.json";
import type { Provenance } from "@/lib/agent/provenance";

/**
 * The clickable manual view. Geometry comes from knowledge/hotspots.json, which is
 * build-generated by scripts/hotspots.py from the manual's own callout pages — never
 * hand-placed here.
 *
 * The overlay is SVG rather than positioned divs for two reasons: viewBox does the
 * responsive scaling, so coordinates are used exactly as the corpus emits them, and
 * irregular parts can become polygons later without rewriting the layer.
 *
 * The camera is one composed transform — translate then scale, with the origin pinned at
 * 0 0 — rather than a bare scale around a moving transform-origin. Origin changes are not
 * interpolable, so animating scale while the origin jumps makes the image snap to the new
 * anchor and only then glide. Composing both into a single matrix lets one transition
 * carry the whole move, and gives wheel zoom and drag somewhere to write to.
 */

type Point = { x: number; y: number };

type Shape =
  | { type: "circle"; r: number }
  // The interior camera is off-axis, so round parts project as ellipses.
  | { type: "ellipse"; rx: number; ry: number }
  | { type: "rect"; w: number; h: number }
  | { type: "polygon"; points: Point[] };

type HotspotPart = {
  id: string;
  label: string;
  description: string;
  center: { x: number; y: number };
  center_px: { x: number; y: number };
  shape: Shape;
  zoom: number;
  geometry_method: "projected" | "measured";
  provenance: Provenance;
  description_provenance: Provenance;
  /** Set when this part sits bodily inside another, e.g. a knob on a casting. */
  parent?: string;
};

/** A whole area rather than a control: click it to frame that part of the machine.
 *  Regions carry no description because the manual does not name them. */
type HotspotRegion = {
  id: string;
  label: string;
  center: { x: number; y: number };
  center_px: { x: number; y: number };
  shape: { type: "rect"; w: number; h: number };
  zoom: number;
};

type HotspotView = {
  image: string;
  size: { width: number; height: number };
  regions?: HotspotRegion[];
  parts: HotspotPart[];
};

/** Camera: x and y are fractions of the stage; scale multiplies the fitted image. */
type Camera = { x: number; y: number; scale: number };

const VIEWS = hotspotData.views as unknown as Record<string, HotspotView>;
const IMAGES: Record<string, typeof frontImage> = {
  front: frontImage,
  inside: insideImage,
};

const VIEW_LABEL: Record<string, string> = { front: "Front view", inside: "Inside view" };
const STAGE_TITLE: Record<string, string> = { front: "Front Panel", inside: "Inside View" };
const VIEW_ORDER = ["front", "inside"];

const FIT: Camera = { x: 0, y: 0, scale: 1 };
const MIN_SCALE = 1;
// 1:1 with the source lands near 1.7x and twice native near 3.4x; a little headroom past
// that is allowed for inspection rather than forbidden outright.
const MAX_SCALE = 4.0;
const DRAG_THRESHOLD_PX = 4;

const clamp = (value: number, low: number, high: number) =>
  Math.min(high, Math.max(low, value));

/** Keep the image covering the stage, so panning never reveals the backing panel. */
function clampCamera({ x, y, scale }: Camera): Camera {
  const limit = 1 - scale;
  return { scale, x: clamp(x, limit, 0), y: clamp(y, limit, 0) };
}

/** Camera that puts a normalised image point in the middle of the stage. */
function frame(cx: number, cy: number, scale: number): Camera {
  return clampCamera({ x: 0.5 - cx * scale, y: 0.5 - cy * scale, scale });
}

export function InteractiveView({
  view: initialView = "front",
  onBack,
}: {
  view?: string;
  onBack?: () => void;
}) {
  const [view, setView] = useState(initialView);
  const data = VIEWS[view];
  const stageRef = useRef<HTMLDivElement>(null);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [hoveredId, setHoveredId] = useState<string | null>(null);
  const [camera, setCamera] = useState<Camera>(FIT);
  // Clicks animate; wheel and drag must track the input directly or they feel laggy.
  const [animate, setAnimate] = useState(true);
  const [sourceOpen, setSourceOpen] = useState(false);

  const selected = data.parts.find((part) => part.id === selectedId) ?? null;
  const hovered = data.parts.find((part) => part.id === hoveredId) ?? null;

  const reset = useCallback(() => {
    setAnimate(true);
    setSelectedId(null);
    setSourceOpen(false);
    setCamera(FIT);
  }, []);

  const focusRegion = useCallback((region: HotspotRegion) => {
    setAnimate(true);
    setSelectedId(null);
    setSourceOpen(false);
    setCamera(frame(region.center.x, region.center.y, region.zoom));
  }, []);

  const select = useCallback(
    (part: HotspotPart) => {
      if (part.id === selectedId) {
        reset();
        return;
      }
      setAnimate(true);
      setSelectedId(part.id);
      setSourceOpen(false);
      setCamera(frame(part.center.x, part.center.y, part.zoom));
    },
    [selectedId, reset],
  );

  // Views are separate images with separate coordinate spaces, so a camera or selection
  // carried across would point at nothing.
  const switchView = useCallback((next: string) => {
    setView(next);
    setSelectedId(null);
    setHoveredId(null);
    setSourceOpen(false);
    setAnimate(false);
    setCamera(FIT);
  }, []);

  useEffect(() => {
    const onKey = (event: KeyboardEvent) => {
      if (event.key === "Escape") reset();
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [reset]);

  // The popover is a transient overlay, so anything else you click should dismiss it.
  useEffect(() => {
    if (!sourceOpen) return;
    const onClick = () => setSourceOpen(false);
    document.addEventListener("click", onClick);
    return () => document.removeEventListener("click", onClick);
  }, [sourceOpen]);

  // React attaches wheel listeners passively, which forbids preventDefault, so the page
  // would scroll behind the zoom. A native non-passive listener is the only way to hold
  // the gesture. Trackpad pinch arrives here too, as a wheel event with ctrlKey set.
  useEffect(() => {
    const stage = stageRef.current;
    if (!stage) return;

    const onWheel = (event: WheelEvent) => {
      event.preventDefault();
      const rect = stage.getBoundingClientRect();
      const pointerX = (event.clientX - rect.left) / rect.width;
      const pointerY = (event.clientY - rect.top) / rect.height;

      setAnimate(false);
      setCamera((current) => {
        const factor = Math.exp(-event.deltaY * (event.ctrlKey ? 0.01 : 0.0018));
        const scale = clamp(current.scale * factor, MIN_SCALE, MAX_SCALE);
        if (scale === current.scale) return current;
        // Hold whatever sits under the cursor still while the scale changes.
        const ratio = scale / current.scale;
        return clampCamera({
          scale,
          x: pointerX - (pointerX - current.x) * ratio,
          y: pointerY - (pointerY - current.y) * ratio,
        });
      });
    };

    stage.addEventListener("wheel", onWheel, { passive: false });
    return () => stage.removeEventListener("wheel", onWheel);
  }, []);

  // Drag to pan. Without it, wheel zoom leaves you stuck looking at the middle.
  const drag = useRef<{ id: number; x: number; y: number; moved: boolean } | null>(null);

  const onPointerDown = (event: React.PointerEvent<HTMLDivElement>) => {
    if (event.button !== 0) return;
    drag.current = { id: event.pointerId, x: event.clientX, y: event.clientY, moved: false };
  };

  const onPointerMove = (event: React.PointerEvent<HTMLDivElement>) => {
    const state = drag.current;
    const stage = stageRef.current;
    if (!state || state.id !== event.pointerId || !stage) return;

    const dx = event.clientX - state.x;
    const dy = event.clientY - state.y;
    if (!state.moved && Math.hypot(dx, dy) < DRAG_THRESHOLD_PX) return;
    if (!state.moved) {
      state.moved = true;
      stage.setPointerCapture(event.pointerId);
    }

    const rect = stage.getBoundingClientRect();
    state.x = event.clientX;
    state.y = event.clientY;
    setAnimate(false);
    setCamera((current) =>
      clampCamera({ ...current, x: current.x + dx / rect.width, y: current.y + dy / rect.height }),
    );
  };

  const endDrag = (event: React.PointerEvent<HTMLDivElement>) => {
    const state = drag.current;
    if (state?.moved) stageRef.current?.releasePointerCapture(event.pointerId);
    // A drag that ends over the background must not read as a click-to-dismiss.
    if (state && !state.moved && event.target === event.currentTarget) reset();
    drag.current = null;
  };

  const { width, height } = data.size;
  const zoomed = camera.scale > 1.001;
  const nextView = VIEW_ORDER[(VIEW_ORDER.indexOf(view) + 1) % VIEW_ORDER.length];

  // The chip tracks the part through the camera, so it stays on the control while zoomed.
  const chipLeft = hovered ? (camera.x + hovered.center.x * camera.scale) * 100 : 0;
  const chipTop = hovered ? (camera.y + hovered.center.y * camera.scale) * 100 : 0;

  return (
    <div className="explorer">
      <header className="explorer-head">
        <button type="button" className="back-button" onClick={onBack}>
          <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.75" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
            <line x1="19" y1="12" x2="6" y2="12" />
            <polyline points="12,6 6,12 12,18" />
          </svg>
          Back to chat
        </button>

        <div className="explorer-head-right">
          <span className="pov-label">{VIEW_LABEL[view]}</span>
          <button type="button" className="pov-toggle" onClick={() => switchView(nextView)}>
            <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.75" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
              <polyline points="16,4 21,9 16,14" />
              <path d="M21 9H8a5 5 0 0 0 0 10h1" />
            </svg>
            {VIEW_LABEL[nextView]}
          </button>
        </div>
      </header>

      <div className="explorer-body">
        <h1 className="stage-title">{STAGE_TITLE[view]}</h1>

        <div
          ref={stageRef}
          className={`stage${zoomed ? " is-zoomed" : ""}`}
          style={{ aspectRatio: `${width} / ${height}` }}
          onPointerDown={onPointerDown}
          onPointerMove={onPointerMove}
          onPointerUp={endDrag}
          onPointerCancel={endDrag}
          role="presentation"
        >
          <div
            className={`stage-zoomer${animate ? " is-animated" : ""}`}
            style={{
              transform: `translate(${camera.x * 100}%, ${camera.y * 100}%) scale(${camera.scale})`,
            }}
          >
            <Image
              src={IMAGES[view]}
              alt={`Vulcan OmniPro 220, ${view} view`}
              fill
              sizes="(max-width: 760px) 92vw, 560px"
              priority
              draggable={false}
            />
            <svg
              className="hotspot-layer"
              viewBox={`0 0 ${width} ${height}`}
              preserveAspectRatio="xMidYMid meet"
              aria-label="Machine parts"
            >
              {(data.regions ?? []).map((region) => (
                <g
                  key={region.id}
                  className="hotspot-region"
                  role="button"
                  tabIndex={0}
                  aria-label={`Zoom to ${region.label.toLowerCase()}`}
                  onClick={(event) => {
                    event.stopPropagation();
                    if (drag.current?.moved) return;
                    focusRegion(region);
                  }}
                  onKeyDown={(event) => {
                    if (event.key === "Enter" || event.key === " ") {
                      event.preventDefault();
                      focusRegion(region);
                    }
                  }}
                >
                  <title>{`Zoom to ${region.label.toLowerCase()}`}</title>
                  <rect
                    x={region.center_px.x - (region.shape.w * width) / 2}
                    y={region.center_px.y - (region.shape.h * height) / 2}
                    width={region.shape.w * width}
                    height={region.shape.h * height}
                    rx={10}
                  />
                </g>
              ))}

              {[...data.parts]
                .sort((a, b) => Number("parent" in a) - Number("parent" in b))
                .map((part) => {
                  const isSelected = part.id === selectedId;
                  const isHovered = part.id === hoveredId;
                  return (
                    <g
                      key={part.id}
                      className={`hotspot${isSelected ? " is-selected" : ""}${
                        isHovered ? " is-hovered" : ""
                      }`}
                      role="button"
                      tabIndex={0}
                      aria-pressed={isSelected}
                      aria-label={part.label}
                      onClick={(event) => {
                        event.stopPropagation();
                        if (drag.current?.moved) return;
                        select(part);
                      }}
                      onKeyDown={(event) => {
                        if (event.key === "Enter" || event.key === " ") {
                          event.preventDefault();
                          select(part);
                        }
                      }}
                      onMouseEnter={() => setHoveredId(part.id)}
                      onMouseLeave={() => setHoveredId(null)}
                      onFocus={() => setHoveredId(part.id)}
                      onBlur={() => setHoveredId(null)}
                    >
                      <title>{part.label}</title>
                      <HotspotShape part={part} width={width} height={height} />
                    </g>
                  );
                })}
            </svg>
          </div>

          {hovered && (
            <div
              className="chip"
              style={{ left: `${chipLeft}%`, top: `calc(${chipTop}% - 34px)` }}
              aria-hidden="true"
            >
              {hovered.label}
            </div>
          )}

          {zoomed && (
            <button type="button" className="stage-reset" onClick={reset}>
              Reset view
            </button>
          )}
        </div>

        <div className="detail" aria-live="polite">
          {selected ? (
            <>
              <div className="detail-head">
                <h2>{selected.label}</h2>
                <button type="button" className="detail-close" onClick={reset}>
                  Close
                </button>
              </div>
              <p className="detail-body">{selected.description}</p>
              <div className="source-anchor">
                <button
                  type="button"
                  className="source-trigger"
                  aria-expanded={sourceOpen}
                  onClick={(event) => {
                    event.stopPropagation();
                    setSourceOpen((open) => !open);
                  }}
                >
                  Source
                </button>
                {sourceOpen && (
                  <div className="source-popover" onClick={(event) => event.stopPropagation()}>
                    <div className="source-popover-label">Sources</div>
                    <SourceRow title="What it does" provenance={selected.description_provenance} />
                    <SourceRow title="Where it is" provenance={selected.provenance} />
                    {selected.geometry_method === "projected" && (
                      <p className="source-note">
                        Outline projected from the manual&rsquo;s callout drawing onto the
                        photograph rather than measured on the machine.
                      </p>
                    )}
                  </div>
                )}
              </div>
            </>
          ) : (
            <p className="detail-hint">
              Hover any control to name it; click to zoom in and read what it does.{" "}
              {data.parts.length} parts are labelled from the manual. Scroll to zoom, drag to
              pan, Esc resets the view.
            </p>
          )}
        </div>
      </div>
    </div>
  );
}

/** One provenance line in the popover. Tier is spelled out rather than colour-coded here:
 *  the popover is small, and the three tiers must never blur (CLAUDE.md). */
function SourceRow({ title, provenance }: { title: string; provenance: Provenance }) {
  return (
    <div className="source-row">
      <span className={`source-tier tier-${provenance.tier}`}>T{provenance.tier}</span>
      <span>
        <span className="source-row-title">{title}</span>
        <span className="source-row-detail">
          {docName(provenance.source)}
          {provenance.tier === 1 && provenance.page ? `, p. ${provenance.page}` : ""}
          {provenance.tier === 1 && provenance.figure ? ` (${provenance.figure})` : ""}
          {provenance.tier === 2 ? ` — ${provenance.url}` : ""}
          {provenance.tier === 3 ? ` — ${provenance.basis}` : ""}
        </span>
      </span>
    </div>
  );
}

/** Source paths are file paths in the corpus; the popover shows a document name. */
function docName(source: string): string {
  const base = source.split("/").pop() ?? source;
  const stem = base.replace(/\.[a-z0-9]+$/i, "").replace(/[-_]+/g, " ");
  return stem.replace(/\b[a-z]/g, (letter) => letter.toUpperCase());
}

/** Draws one hit region. Polygons exist so irregular castings and levers get real
 *  outlines instead of a bounding box that swallows their neighbours. */
function HotspotShape({
  part,
  width,
  height,
}: {
  part: HotspotPart;
  width: number;
  height: number;
}) {
  const { shape, center_px: c } = part;
  if (shape.type === "circle") {
    return <circle cx={c.x} cy={c.y} r={shape.r * width} />;
  }
  if (shape.type === "ellipse") {
    return <ellipse cx={c.x} cy={c.y} rx={shape.rx * width} ry={shape.ry * height} />;
  }
  if (shape.type === "rect") {
    return (
      <rect
        x={c.x - (shape.w * width) / 2}
        y={c.y - (shape.h * height) / 2}
        width={shape.w * width}
        height={shape.h * height}
        rx={6}
      />
    );
  }
  return (
    <polygon
      points={shape.points.map((p) => `${p.x * width},${p.y * height}`).join(" ")}
    />
  );
}
